version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./inputs:/inputs
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./inputs:/inputs