name: Main Image Creation Flow

on:
  push:
    branches: [ main, 012_build_tag_push_images_to_dockerhub ]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          push: true
          file: { context }/backend/Dockerfile
          tags: lviksne2/mf-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          push: true
          file: { context }/frontend/Dockerfile
          tags: lviksne2/mf-frontend:latest