name: Backend Pull Request Checks
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend-pr:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        working-directory: backend

      - name: Run tests
        run: pytest
        working-directory: backend

      - name: Get coverage
        run: pytest --cov=. --cov-fail-under=90
        working-directory: backend

  backend-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install backend dependencies
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        run: snyk test --skip-unresolved=true
        working-directory: ./backend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  frontend-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install frontend dependencies
        run: pip install -r requirements.txt
        working-directory: frontend

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        run: snyk test --skip-unresolved=true
        working-directory: ./frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check Dockerfile best practices - Backend
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: backend/Dockerfile
          failure-threshold: error

      - name: Check Dockerfile best practices - Frontend
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: frontend/Dockerfile
          failure-threshold: error
