name: Backend Pull Request Checks
on:
#  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend-pr:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        working-directory: app

      - name: Run tests
        run: pytest
        working-directory: app/tests

      - name: Get coverage
        run: pytest --cov=app --cov-fail-under=95 .
        working-directory: app/tests
